-- -328804380 -- Person
-- -632802873 -- AcademicRecord

SELECT 
	io.ID AS object_id,
	ia.NAME AS "FIELD_TYPE",
	COALESCE(ip.VALUE, re.NAME, TO_CHAR(ip.LIST_VALUE_ID)) AS VALUE,
	(CASE WHEN ip.REFERENCE_ID IS NULL THEN 'NO' ELSE 'YES' END) AS IS_REFERENCE
FROM ITMO_OBJECT_TYPES iot, 
	ITMO_ATTRIBUTES ia,
	ITMO_OBJECTS io,
	ITMO_PARAMS ip,
	ITMO_OBJECTS re
WHERE
	iot.ID = -328804380 AND -- Academic Record
	-- io.ID = 129 AND
	io.OBJECT_TYPE_ID = iot.ID AND 
	ip.OBJECT_ID = io.ID AND 
	ia.ID = ip.ATTRIBUTE_ID AND
	re.ID (+)= ip.REFERENCE_ID 
ORDER BY io.id;