DROP TABLE ITMO.ITMO_PARAMS;
DROP TABLE ITMO.ITMO_LIST_VALUES;
DROP TABLE ITMO.ITMO_ATTRIBUTES;
DROP TABLE ITMO.ITMO_OBJECTS;
DROP TABLE ITMO.ITMO_OBJECT_TYPES;
DROP SEQUENCE GENERAL_SEQUENCE;

CREATE TABLE ITMO.ITMO_OBJECT_TYPES (
	ID NUMBER(22,0),
	NAME VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(100),
	CONSTRAINT ITMO_OBJECT_TYPES_PK PRIMARY KEY (ID)
);

CREATE TABLE ITMO.ITMO_OBJECTS (
	ID NUMBER(22,0),
	NAME VARCHAR2(100) NOT NULL,
	OBJECT_TYPE_ID NUMBER(22,0) NOT NULL,
	PARENT_ID NUMBER(22,0),
	CONSTRAINT ITMO_OBJECTS_PK PRIMARY KEY (ID),
	CONSTRAINT FK_ITMO_OBJECT_TYPES FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES ITMO.ITMO_OBJECT_TYPES(ID),
	CONSTRAINT FK_ITMO_PARENT_OBJECTS FOREIGN KEY (PARENT_ID) REFERENCES ITMO.ITMO_OBJECTS(ID)
);

CREATE TABLE ITMO.ITMO_ATTRIBUTES (
	ID NUMBER(22,0),
	NAME VARCHAR2(100)  NOT NULL,
	ATTRIBUTE_TYPE VARCHAR2(100)  NOT NULL,
	CONSTRAINT ITMO_ATTRIBUTES_PK PRIMARY KEY (ID)
);

CREATE TABLE ITMO.ITMO_LIST_VALUES (
	ID NUMBER(22,0),
	VALUE VARCHAR2(100) NOT NULL,
	CONSTRAINT ITMO_LIST_VALUES_PK PRIMARY KEY (ID)
);

CREATE TABLE ITMO.ITMO_PARAMS (
	ID NUMBER(22,0),
	OBJECT_ID NUMBER(22,0) NOT NULL,
	ATTRIBUTE_ID NUMBER(22,0) NOT NULL,
	VALUE VARCHAR2(100),
	LIST_VALUE_ID NUMBER(22,0),
	CONSTRAINT ITMO_PARAMS_PK PRIMARY KEY (ID),
	CONSTRAINT FK_ITMO_ATTRIBUTES FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ITMO.ITMO_ATTRIBUTES(ID),
	CONSTRAINT FK_ITMO_LIST_VALUES FOREIGN KEY (LIST_VALUE_ID) REFERENCES ITMO.ITMO_LIST_VALUES(ID),
	CONSTRAINT FK_ITMO_OBJECTS FOREIGN KEY (OBJECT_ID) REFERENCES ITMO.ITMO_OBJECTS(ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX ITMO_PARAMS_PK ON ITMO.ITMO_PARAMS (ID);

CREATE SEQUENCE GENERAL_SEQUENCE
 START WITH     1
 INCREMENT BY   1
 NOMAXVALUE
 CACHE 20
 NOCYCLE;

CREATE OR REPLACE TRIGGER PARAMS_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_PARAMS 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;
/* 


CREATE OR REPLACE TRIGGER OBJECT_TYPES_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_OBJECT_TYPES 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE OR REPLACE TRIGGER OBJECTS_ON_INSERT
  BEFORE INSERT ON itmo.itmo_objects
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE OR REPLACE TRIGGER ATTRIBUTES_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_ATTRIBUTES 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;


 */