DROP TABLE ITMO.ITMO_OBJECT_TYPES;
CREATE TABLE ITMO.ITMO_OBJECT_TYPES (
	ID NUMBER(22,0),
	NAME VARCHAR2(100),
	DESCRIPTION VARCHAR2(100),
	CONSTRAINT ITMO_OBJECT_TYPES_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C007677 CHECK (ID),
	CONSTRAINT SYS_C007678 CHECK (NAME)
);
CREATE UNIQUE INDEX ITMO_OBJECT_TYPES_PK ON ITMO.ITMO_OBJECT_TYPES (ID);

DROP TABLE ITMO.ITMO_OBJECTS;
CREATE TABLE ITMO.ITMO_OBJECTS (
	ID NUMBER(22,0),
	NAME VARCHAR2(100),
	OBJECT_TYPE_ID NUMBER(22,0),
	PARENT_ID NUMBER(22,0),
	CONSTRAINT ITMO_OBJECTS_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C007666 CHECK (ID),
	CONSTRAINT SYS_C007667 CHECK (NAME),
	CONSTRAINT SYS_C007668 CHECK (OBJECT_TYPE_ID),
	CONSTRAINT FK_ITMO_OBJECT_TYPES FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES ITMO.ITMO_OBJECT_TYPES(ID)
);
CREATE UNIQUE INDEX ITMO_OBJECTS_PK ON ITMO.ITMO_OBJECTS (ID);

DROP TABLE ITMO.ITMO_ATTRIBUTES;
CREATE TABLE ITMO.ITMO_ATTRIBUTES (
	ID NUMBER(22,0),
	NAME VARCHAR2(100),
	ATTRIBUTE_TYPE VARCHAR2(100),
	CONSTRAINT ITMO_ATTRIBUTES_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C007670 CHECK (ID),
	CONSTRAINT SYS_C007671 CHECK (NAME),
	CONSTRAINT SYS_C007672 CHECK (ATTRIBUTE_TYPE)
);
CREATE UNIQUE INDEX ITMO_ATTRIBUTES_PK ON ITMO.ITMO_ATTRIBUTES (ID);

DROP TABLE ITMO.ITMO_LIST_VALUES;
CREATE TABLE ITMO.ITMO_LIST_VALUES (
	ID NUMBER(22,0),
	VALUE VARCHAR2(100),
	CONSTRAINT ITMO_LIST_VALUES_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C007682 CHECK (ID),
	CONSTRAINT SYS_C007683 CHECK (VALUE)
);
CREATE UNIQUE INDEX ITMO_LIST_VALUES_PK ON ITMO.ITMO_LIST_VALUES (ID);

DROP TABLE ITMO.ITMO_PARAMS;
CREATE TABLE ITMO.ITMO_PARAMS (
	ID NUMBER(22,0),
	OBJECT_ID NUMBER(22,0),
	ATTR_ID NUMBER(22,0),
	VALUE VARCHAR2(100),
	LIST_VALUE_ID NUMBER(22,0),
	CONSTRAINT ITMO_PARAMS_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C007680 CHECK (OBJECT_ID),
	CONSTRAINT SYS_C007681 CHECK (ATTR_ID),
	CONSTRAINT FK_ITMO_ATTRIBUTES FOREIGN KEY (ATTR_ID) REFERENCES ITMO.ITMO_ATTRIBUTES(ID),
	CONSTRAINT FK_ITMO_LIST_VALUES FOREIGN KEY (LIST_VALUE_ID) REFERENCES ITMO.ITMO_LIST_VALUES(ID),
	CONSTRAINT FK_ITMO_OBJECTS FOREIGN KEY (OBJECT_ID) REFERENCES ITMO.ITMO_OBJECTS(ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX ITMO_PARAMS_PK ON ITMO.ITMO_PARAMS (ID);

CREATE SEQUENCE GENERAL_SEQUENCE
 START WITH     1
 INCREMENT BY   1
 NOMAXVALUE
 CACHE 20
 NOCYCLE;

CREATE OR REPLACE TRIGGER OBJECT_TYPES_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_OBJECT_TYPES 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE OR REPLACE TRIGGER OBJECTS_ON_INSERT
  BEFORE INSERT ON itmo.itmo_objects
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE OR REPLACE TRIGGER ATTRIBUTES_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_ATTRIBUTES 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE OR REPLACE TRIGGER LIST_VALUES_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_LIST_VALUES 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE OR REPLACE TRIGGER PARAMS_ON_INSERT
  BEFORE INSERT ON itmo.ITMO_PARAMS 
  FOR EACH ROW
BEGIN
  SELECT general_sequence.nextval
  INTO :new.id
  FROM dual;
END;

